version: '3.8'
services:
  travel-calculator-api:
    build:
      context: ../
      dockerfile: build-deploy/Dockerfile.app
    env_file: ../.env
    image: travel_calculator_api:latest
    container_name: travel-calculator-api
    volumes:
      - socket-data:/home/tmp/gunicorn

  travel-calculator-nginx:
    build:
      context: ../
      dockerfile: build-deploy/Dockerfile.nginx
    image: travel_calculator_nginx:latest
    container_name: travel-calculator-nginx
    ports:
      - "80:80"
    volumes:
      - socket-data:/etc/nginx/gunicorn
    depends_on:
      - travel-calculator-api
    links:
      - travel-calculator-api
volumes:
  socket-data:
